### ISSUE TITLE
A Visual Studio Crash was caused  by PerfGraphVSIX

### ISSUE THREAD

**Issue by jtbrower** [calvinhsia/PerfGraphVSIX#9]
Hello Calvin, I have been in contact with you through the Visual Studio developer communities bug and error reporting system.  I installed your VS extension in 16.7.0 Preview 3.1.  After install I began clicking on the tab pages of your extension.  I saw a stack trace displayed in your tools Window, then clicked on one of your sample source code files and Visual Studio immediately crashed.  I have attached the crash dump  wrapped in a zip file.  If you find personal information in this file that may put me at risk for sharing this publicly then please remove it.  It might be easier if we start a conversion through email.

[devenv.exe.7580.zip](https://github.com/calvinhsia/PerfGraphVSIX/files/4833158/devenv.exe.7580.zip)

**Comment by calvinhsia** [comment]
Thanks for the report Jason,
That particular crash is because of a Dbl-Click on a TreeView item in the Code Samples window
Line 93 of this:
https://github.com/calvinhsia/PerfGraphVSIX/blob/master/PerfGraphVSIX/UserControls/CodeSamples.xaml.cs

I don't understand how that could crash: it is a button event which can only occur on the UI thread, and the crash is on the UI thread. I wonder if something is different about your installation (my extension uses the VS SDK from your installation).
Did you install the VS Extensions workload from the VS Installer? I'm pretty sure  it's not required, but that be related.

In any case, if you avoid dbl-clicking the treeview item, that will avoid that code.

**Comment by calvinhsia** [comment]
also, other folks have dbl-clicked and not had any problems. hmm...

**Comment by jtbrower** [comment]
I just checked and indeed the Visual Studio extensions workload is installed.  I wish I had more time to help figure out why this crash occurred with this tool but as you know my original problem is the fact that Visual Studio keeps crashing.  If my brain becomes fatigued with primary tasks I will try to come back to this and avoid double clicking on the tree view items.

**Comment by calvinhsia** [comment]
fixed in latest release v1.1.1.451. Thanks Jason!

**Comment by jtbrower** [comment]
Thank you Calvin, I will try to find time to give it a shot later.
